### ISSUE TITLE
I have created an API

### ISSUE THREAD

**Issue by mrwoofa** [stashapp/metadata-api-discuss#5]
A couple months ago i created a database full of scenes from various sites.

It currently has 200,000 scenes, 50,000 performers and 350 different sites/studios.

It has fulltext search, along with endpoints to get Performers/Scenes/Sites and relevent details. 

It also keeps a copy of images, served via a CDN.

The only problem is, i don't really want to opensource the codebase, and i don't have the money to host it to the public.

I've been using it with Plex as a scraper, and it does a pretty good job.

Maybe we could collaborate?

**Comment by Leopere** [comment]
I can't really say no to that, jump into our Discord :) Just not sure how we can if it's not public and not open-source but we're receptive to contributions anyways.  Even if you can help us with our first data for our dataset which we can test our tooling against that's useful!

**Comment by Leopere** [comment]
@mrwoofa https://discord.gg/8ZqDCT
